name: Linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'    # ĐỔI TỪ 3.11 THÀNH 3.12

    - name: Install linters
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 isort

    - name: Run black
      run: |
        cd code
        black --check .

    - name: Run isort
      run: |
        cd code
        isort --check-only .

    - name: Run flake8
      run: |
        cd code
        flake8 . --max-line-length=88 --extend-ignore=E203,W503